name: "🚀 release"
on:
 push:
  branches:
    - main

jobs:
  release:
    name: 🚀 release
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org
    - name: Install peer dependencies
      run: yarn add react@>=16.8.0 && yarn add react-native>=0.59.0 && yarn add react-native-reanimated@>=3.0.0
    - name: Install dependencies
      run: yarn install
    - name: Build project
      run: yarn build
    - name: Release
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}